In [3]:
import pandas as pd

In [10]:
cities = pd.read_csv("cities1000.txt", sep="\t", header=None)
states = pd.read_csv("admin1CodesASCII.txt", sep="\t", header=None)

C:\Users\HP\AppData\Local\Temp\ipykernel_5748\4090271903.py:1: DtypeWarning: Columns (10,13) have mixed types. Specify dtype option on import or set low_memory=False.
  cities = pd.read_csv("cities1000.txt", sep="\t", header=None)

In [15]:
cities

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,3038832,Vila,Vila,"Casas Vila,Vila",42.53176,1.56654,P,PPL,AD,NaN,03,NaN,NaN,NaN,1418,NaN,1318,Europe/Andorra,2024-11-04
1,3039154,El Tarter,El Tarter,"Ehl Tarter,El Tarter,El Tarter - Principau d'A...",42.57952,1.65362,P,PPL,AD,NaN,02,NaN,NaN,NaN,1052,NaN,1721,Europe/Andorra,2012-11-03
2,3039163,Sant Julià de Lòria,Sant Julia de Loria,"San Julia,San Julià,Sant Julia de Loria,Sant J...",42.46372,1.49129,P,PPLA,AD,NaN,06,NaN,NaN,NaN,8022,NaN,921,Europe/Andorra,2013-11-23
3,3039181,Santa Coloma,Santa Coloma,Santa Coloma,42.49454,1.49897,P,PPL,AD,NaN,07,NaN,NaN,NaN,3236,NaN,978,Europe/Andorra,2026-02-07
4,3039604,Pas de la Casa,Pas de la Casa,"Pas de la Kasa,Пас де ла Каса",42.54277,1.73361,P,PPL,AD,NaN,03,NaN,NaN,NaN,2363,2050.0,2106,Europe/Andorra,2008-06-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166898,895417,Banket,Banket,"Banket,Banket Junction",-17.38333,30.40000,P,PPL,ZW,NaN,5.0,NaN,NaN,NaN,9845,NaN,1277,Africa/Harare,2024-12-02
166899,1085510,Epworth,Epworth,Epworth,-17.89000,31.14750,P,PPLX,ZW,NaN,10.0,NaN,NaN,NaN,206368,NaN,1508,Africa/Harare,2024-12-02
166900,1106542,Chitungwiza,Chitungwiza,"Chitungviza,Chitungwiza,Chytungviza,Citungviza...",-18.01274,31.07555,P,PPL,ZW,NaN,10.0,NaN,NaN,NaN,371246,NaN,1435,Africa/Harare,2024-12-02
166901,13132735,Harare Western Suburbs,Harare Western Suburbs,NaN,-17.84150,30.87674,P,PPL,ZW,NaN,5.0,NaN,NaN,NaN,15556,NaN,1460,Africa/Harare,2024-12-02
166902,13132736,Mhangura Mine,Mhangura Mine,NaN,-16.89196,30.15902,P,PPL,ZW,NaN,5.0,NaN,NaN,NaN,2930,NaN,1142,Africa/Harare,2024-12-02

In [11]:
states

          0                          1                          2        3
0     AD.06        Sant Julià de Loria        Sant Julia de Loria  3039162
1     AD.05                     Ordino                     Ordino  3039676
2     AD.04                 La Massana                 La Massana  3040131
3     AD.03                     Encamp                     Encamp  3040684
4     AD.02                    Canillo                    Canillo  3041203
...     ...                        ...                        ...      ...
3857  ZW.04  Mashonaland East Province  Mashonaland East Province   886842
3858  ZW.03        Mashonaland Central        Mashonaland Central   886843
3859  ZW.01                 Manicaland                 Manicaland   887358
3860  ZW.09                   Bulawayo                   Bulawayo  1105843
3861  ZW.10                     Harare                     Harare  1105844

[3862 rows x 4 columns]

In [12]:
india = cities[cities[8] == "IN"]

india["state_code"] = "IN." + india[10].astype(str)

merged = india.merge(states, left_on="state_code", right_on=0)

C:\Users\HP\AppData\Local\Temp\ipykernel_5748\2479883507.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  india["state_code"] = "IN." + india[10].astype(str)

In [6]:
merged.head(2)

,0_x,1_x,2_x,3_x,4,5,6,7,8,9,...,14,15,16,17,18,state_code,0_y,1_y,2_y,3_y
0,1163626,Thang,Thang,NaN,34.92740,76.79336,P,PPL,IN,NaN,...,1622,3890.0,2726,Asia/Kolkata,2023-09-23,IN.41,IN.41,Ladakh,Ladakh,12096464
1,1167718,Pūnch,Punch,"Poonch,Punch,Pūnch,bwnsh,bwntsh,pwnchھ,بونتش,ب...",33.77033,74.09254,P,PPL,IN,NaN,...,28197,NaN,999,Asia/Kolkata,2024-01-06,IN.12,IN.12,Jammu and Kashmir,Jammu and Kashmir,1269320

In [7]:
merged['state'] = merged['1_y']
merged['city'] = merged['1_x']
merged['latitude'] = merged[4]
merged['longitude'] = merged[5]
df = merged[['state_code','state','city','latitude','longitude']]

In [8]:
df['state'].value_counts()

state
Tamil Nadu                                  1061
Maharashtra                                  550
Kerala                                       523
Uttar Pradesh                                501
Madhya Pradesh                               475
Karnataka                                    374
Gujarat                                      374
Rajasthan                                    311
Andhra Pradesh                               258
Jharkhand                                    235
Assam                                        226
Punjab                                       223
Odisha                                       221
Bihar                                        218
Chhattisgarh                                 192
Telangana                                    185
West Bengal                                  183
Haryana                                      161
Jammu and Kashmir                            129
Delhi                                        120
Goa                                           78
Himachal Pradesh                              67
Uttarakhand                                   53
Tripura                                       42
Manipur                                       42
Arunachal Pradesh                             34
Mizoram                                       24
Nagaland                                      22
Meghalaya                                     20
Dadra and Nagar Haveli and Daman and Diu      15
Sikkim                                        10
Puducherry                                    10
Lakshadweep                                    9
Andaman and Nicobar                            9
Ladakh                                         6
Chandigarh                                     5
Name: count, dtype: int64

In [33]:
df.to_csv("State_geo_list.csv",index = False)